/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a.miniproyecto3;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author JHOIMAR
 */
public class VentanaAgendarCitas extends javax.swing.JFrame {
    //VentanaDeAfiliacion v1 = new VentanaDeAfiliacion();
    /*public boolean ValidarUsuario(int ID){
        boolean resultado = false;
        for(int i = 0; i<v1.UsuarioPacientes.size() && resultado == false; i++){
            if(ID==v1.UsuarioPacientes.get(i).getDocumento()){
                resultado = true;
            }
        }
        
        return resultado;
    }*/
    
    
    ArrayList<CitaAgendada> PacientesAgendados = new ArrayList();
    public VentanaAgendarCitas() {
        initComponents();
        setSize(600, 550);
        setLocationRelativeTo(null);
        setResizable(false);
        setMinimumSize(new Dimension(200,200));
        this.getContentPane().setBackground(Color.white);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BoxGenero = new javax.swing.JComboBox<>();
        BoxServicio = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        BoxHorario = new javax.swing.JComboBox<>();
        ID = new javax.swing.JTextField();
        NombrePaciente = new javax.swing.JTextField();
        ApellidoPaciente = new javax.swing.JTextField();
        TelPaciente = new javax.swing.JTextField();
        hora = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        GuardarCita = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        BoxConsultorio = new javax.swing.JComboBox<>();
        TFielFechaCita = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("HACER UNA CITA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 10, 230, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NOMBRE DEL PACIENTE: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 140, 150, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DOCUMENTO DE IDENTIDAD");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 90, 210, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("APELLIDOS DEL PACIENTE:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 200, 170, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TELEFONO:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 260, 80, 16);

        BoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOMBRE", "MUJER", " " }));
        BoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxGeneroActionPerformed(evt);
            }
        });
        jPanel1.add(BoxGenero);
        BoxGenero.setBounds(370, 230, 100, 22);

        BoxServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ODONTOLOGÍA", "EXÁMENES DE LABORATORIOS", "CITAS MEDICAS GENERAL", "CITAS CON ESPECIALISTAS", " " }));
        jPanel1.add(BoxServicio);
        BoxServicio.setBounds(20, 330, 330, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("HORA: ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(370, 140, 50, 30);

        BoxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A.M", "P.M" }));
        jPanel1.add(BoxHorario);
        BoxHorario.setBounds(480, 170, 80, 22);

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDKeyTyped(evt);
            }
        });
        jPanel1.add(ID);
        ID.setBounds(20, 110, 330, 22);

        NombrePaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombrePacienteKeyTyped(evt);
            }
        });
        jPanel1.add(NombrePaciente);
        NombrePaciente.setBounds(20, 170, 330, 22);

        ApellidoPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApellidoPacienteKeyTyped(evt);
            }
        });
        jPanel1.add(ApellidoPaciente);
        ApellidoPaciente.setBounds(20, 230, 330, 22);

        TelPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelPacienteKeyTyped(evt);
            }
        });
        jPanel1.add(TelPaciente);
        TelPaciente.setBounds(20, 280, 330, 22);

        hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaActionPerformed(evt);
            }
        });
        hora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                horaKeyTyped(evt);
            }
        });
        jPanel1.add(hora);
        hora.setBounds(370, 170, 100, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("GENERO: ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(370, 200, 70, 16);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("SERVICIO MEDICO: ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 310, 150, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("FECHA: ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 90, 60, 20);

        GuardarCita.setText("GUARDAR");
        GuardarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCitaActionPerformed(evt);
            }
        });
        jPanel1.add(GuardarCita);
        GuardarCita.setBounds(250, 450, 110, 40);

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(370, 450, 110, 40);

        jButton3.setText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(150, 450, 90, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("CONSULTORIO: ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(370, 260, 100, 16);

        BoxConsultorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel1.add(BoxConsultorio);
        BoxConsultorio.setBounds(370, 280, 100, 22);
        jPanel1.add(TFielFechaCita);
        TFielFechaCita.setBounds(370, 110, 190, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxGeneroActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Aca va el boton de cancelar
        VentanaInicio v1Inicio = new VentanaInicio();
        v1Inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Aca va el boton de limpiar
        Limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaActionPerformed

    
    }//GEN-LAST:event_horaActionPerformed

    private void horaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horaKeyTyped
        //Aca solo permito que ingrese números a la hora
        char verificarHora = evt.getKeyChar();
        if(Character.isLetter(verificarHora)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "SOLO SE PERMITEN CARACTERES NÚMERICOS");
        }
    }//GEN-LAST:event_horaKeyTyped

    private void TelPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelPacienteKeyTyped
        // Aca verifico que solo sean caracteres numericos
        char verificartelefono = evt.getKeyChar();
        if(Character.isLetter(verificartelefono)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "SOLO SE PERMITEN CARACTERES NÚMERICOS");
        }
    }//GEN-LAST:event_TelPacienteKeyTyped

    private void IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDKeyTyped
        //Aca verifico que solo se perimitan numero en el ID
        char verificarID = evt.getKeyChar();
        if(Character.isLetter(verificarID)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "SOLO SE PERMITEN CARACTERES NÚMERICOS");
        }
    }//GEN-LAST:event_IDKeyTyped

    private void NombrePacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombrePacienteKeyTyped
        // Valido que solo permita texto en el nombre
        char validartxt = evt.getKeyChar();
        
        if(Character.isDigit(validartxt)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "INGRESE SOLO TEXTO");
        }
    }//GEN-LAST:event_NombrePacienteKeyTyped

    private void ApellidoPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoPacienteKeyTyped
        // Valido que solo permita texto en el apellido
        char validartxt = evt.getKeyChar();
        
        if(Character.isDigit(validartxt)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "INGRESE SOLO TEXTO");
        }
    }//GEN-LAST:event_ApellidoPacienteKeyTyped

    private void GuardarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCitaActionPerformed
        /* Aca se guardan los datos ingresados
        CitaAgendada DatosGuardados;
        
        int Ndocumento;
        String CitaNombre;
        String CitaApellido;
        int CitaTelefono;
        int CitaFecha;
        int CitaHora;
        String CitaGenero = "";
        String CitaConsultorio = "";
        String CitaHorario = "";
        String ServicioMedico = "";
        
        Ndocumento = Integer.parseInt(ID.getText());
        CitaNombre = NombrePaciente.getText();
        CitaApellido = ApellidoPaciente.getText();
        CitaTelefono = Integer.parseInt(TelPaciente.getText());
        CitaFecha = Integer.parseInt(TFielFechaCita.getText());
        CitaHora = Integer.parseInt(hora.getText());
        CitaGenero = BoxGenero.getSelectedItem().toString();
        CitaConsultorio = BoxConsultorio.getSelectedItem().toString();
        CitaHorario = BoxHorario.getSelectedItem().toString();
        ServicioMedico = BoxServicio.getSelectedItem().toString();
        
        if(evt.getSource()==GuardarCita){
            //if(ValidarUsuario(Ndocumento)){
                DatosGuardados = new CitaAgendada(Ndocumento,CitaNombre,CitaApellido,CitaTelefono,CitaFecha,CitaHora,CitaGenero,CitaConsultorio,CitaHorario,ServicioMedico);
                PacientesAgendados.add(DatosGuardados);
                JOptionPane.showMessageDialog(rootPane, "SE HA GUARDADO CORRECTAMENTE");
                //System.out.println(CitaApellido);
                Limpiar();
            } /*else{
                JOptionPane.showMessageDialog(rootPane, "DEBE AFILIARCE PRIMERO");
            }
            
        }*/
    }//GEN-LAST:event_GuardarCitaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgendarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgendarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgendarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgendarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaAgendarCitas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoPaciente;
    private javax.swing.JComboBox<String> BoxConsultorio;
    private javax.swing.JComboBox<String> BoxGenero;
    private javax.swing.JComboBox<String> BoxHorario;
    private javax.swing.JComboBox<String> BoxServicio;
    private javax.swing.JButton GuardarCita;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField NombrePaciente;
    private javax.swing.JTextField TFielFechaCita;
    private javax.swing.JTextField TelPaciente;
    private javax.swing.JTextField hora;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
       ID.setText("");
       NombrePaciente.setText("");
       ApellidoPaciente.setText("");
       TelPaciente.setText("");
       hora.setText("");
    }
}
