/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a.miniproyecto3;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author JHOIMAR
 */
public class VentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogin
     */
    private VentanaInicio padre;
    private VentanaAdministracion administracion;

    public VentanaLogin(
            VentanaAdministracion administracion
    ) {
        initComponents();
        setSize(400, 340);
        setLocationRelativeTo(null);
        setResizable(false);
        setMinimumSize(new Dimension(200, 200));
        this.getContentPane().setBackground(Color.white);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        administracion.setPadre(this);
        this.administracion = administracion;
    }

    public void setPadre(VentanaInicio padre) {
        this.padre = padre;
    }

    public void volver() {
        this.FieldUsuario.setText("");
        this.FieldContraseña.setText("");

        this.administracion.setVisible(false);
        this.setVisible(false);
        this.padre.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        LabelContraseña = new javax.swing.JLabel();
        FieldUsuario = new javax.swing.JTextField();
        FieldContraseña = new javax.swing.JPasswordField();
        ButtonIngresar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LOGIN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 10, 90, 40);

        LabelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(0, 0, 0));
        LabelUsuario.setText("USUARIO: ");
        jPanel1.add(LabelUsuario);
        LabelUsuario.setBounds(40, 90, 90, 20);

        LabelContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelContraseña.setForeground(new java.awt.Color(0, 0, 0));
        LabelContraseña.setText("CONTRASEÑA: ");
        jPanel1.add(LabelContraseña);
        LabelContraseña.setBounds(20, 140, 150, 20);
        jPanel1.add(FieldUsuario);
        FieldUsuario.setBounds(150, 90, 220, 25);
        jPanel1.add(FieldContraseña);
        FieldContraseña.setBounds(150, 140, 220, 25);

        ButtonIngresar.setText("INGRESAR");
        ButtonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonIngresarMouseClicked(evt);
            }
        });
        ButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonIngresar);
        ButtonIngresar.setBounds(70, 220, 100, 37);

        ButtonCancelar.setText("CANCELAR");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonCancelar);
        ButtonCancelar.setBounds(210, 220, 110, 37);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresarActionPerformed
        // Aca va el boton de ingresar
        String usuario = FieldUsuario.getText();
        String Contraseña = String.valueOf(FieldContraseña.getPassword());

        //String password = new String(TFielContraseña.getPassword());
        if (usuario.isEmpty() || Contraseña.isEmpty()) {

            JOptionPane.showInternalMessageDialog(this, "INGRESE LOS CAMPOS REQUERIDOS");
        } else {
            if (usuario.equals("admin") && Contraseña.equals("admin")) {

                JOptionPane.showMessageDialog(this, "BIENVENIDO ADMIN");

                this.administracion.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "USUARIO O CONTRASEÑA INCORRECTA");
            }

        }
    }//GEN-LAST:event_ButtonIngresarActionPerformed

    private void ButtonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonIngresarMouseClicked
        // Aca va el boton de ingresar


    }//GEN-LAST:event_ButtonIngresarMouseClicked

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        // boton cancelar
        this.padre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonIngresar;
    private javax.swing.JPasswordField FieldContraseña;
    private javax.swing.JTextField FieldUsuario;
    private javax.swing.JLabel LabelContraseña;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
