/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a.miniproyecto3;

import java.awt.Color;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author JHOIMAR
 */
public class VentanaAgendarCitas extends javax.swing.JFrame {

    boolean auxiliar;
    private Almacenamiento almacenamiento;
    private VentanaInicio padre;

    public VentanaAgendarCitas(
            Almacenamiento almacenamiento
    ) {
        initComponents();
        setSize(600, 550);
        setLocationRelativeTo(null);
        setResizable(false);
        setMinimumSize(new Dimension(200, 200));
        this.getContentPane().setBackground(Color.white);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        this.almacenamiento = almacenamiento;
    }

    public void setPadre(VentanaInicio padre) {
        this.padre = padre;
    }

    public boolean ValidarUsuario(String Id) {
        boolean i = false;
        try {
            FileReader fileReaderLeer = new FileReader("Datos.txt");
            BufferedReader escritura = new BufferedReader(fileReaderLeer);
            String posicion = "";
            while ((posicion = escritura.readLine()) != null) {
                if (posicion.indexOf(Id) != -1) {
                    System.out.println("Se ecnontro el registro" + posicion);
                    i = true;
                }
            }
        } catch (IOException e) {
            System.out.println(e);
        }
        return i;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BoxGenero = new javax.swing.JComboBox<>();
        BoxServicio = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        BoxHorario = new javax.swing.JComboBox<>();
        ID = new javax.swing.JTextField();
        hora = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ButtonGuardar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();
        ButtonLimpiar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        BoxConsultorio = new javax.swing.JComboBox<>();
        TFielFechaCita = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("HACER UNA CITA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 10, 230, 60);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("DOCUMENTO DE IDENTIDAD");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 90, 210, 16);

        BoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOMBRE", "MUJER", " " }));
        BoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxGeneroActionPerformed(evt);
            }
        });
        jPanel1.add(BoxGenero);
        BoxGenero.setBounds(370, 230, 100, 22);

        BoxServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ODONTOLOGÍA", "EXÁMENES DE LABORATORIOS", "CITAS MEDICAS GENERAL", "CITAS CON ESPECIALISTAS", " " }));
        jPanel1.add(BoxServicio);
        BoxServicio.setBounds(20, 170, 330, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("HORA: ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(370, 140, 50, 30);

        BoxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A.M", "P.M" }));
        jPanel1.add(BoxHorario);
        BoxHorario.setBounds(480, 170, 80, 22);

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDKeyTyped(evt);
            }
        });
        jPanel1.add(ID);
        ID.setBounds(20, 110, 330, 22);

        hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaActionPerformed(evt);
            }
        });
        hora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                horaKeyTyped(evt);
            }
        });
        jPanel1.add(hora);
        hora.setBounds(370, 170, 100, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("GENERO: ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(370, 200, 70, 16);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("SERVICIO MEDICO: ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 140, 150, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("FECHA: ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 90, 60, 20);

        ButtonGuardar.setText("GUARDAR");
        ButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonGuardar);
        ButtonGuardar.setBounds(250, 450, 110, 40);

        ButtonCancelar.setText("CANCELAR");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonCancelar);
        ButtonCancelar.setBounds(370, 450, 110, 40);

        ButtonLimpiar.setText("LIMPIAR");
        ButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonLimpiar);
        ButtonLimpiar.setBounds(150, 450, 90, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("CONSULTORIO: ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 270, 100, 16);

        BoxConsultorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel1.add(BoxConsultorio);
        BoxConsultorio.setBounds(20, 300, 100, 22);

        TFielFechaCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFielFechaCitaActionPerformed(evt);
            }
        });
        jPanel1.add(TFielFechaCita);
        TFielFechaCita.setBounds(370, 110, 190, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("DOCTOR");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 200, 90, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOCTOR 1", "DOCTOR 2", "DOCTOR 3", "DOCTOR 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(20, 230, 330, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxGeneroActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        //Aca va el boton de cancelar
        this.padre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void ButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpiarActionPerformed
        // Aca va el boton de limpiar
        Limpiar();
    }//GEN-LAST:event_ButtonLimpiarActionPerformed

    private void horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaActionPerformed


    }//GEN-LAST:event_horaActionPerformed

    private void horaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horaKeyTyped
        //Aca solo permito que ingrese números a la hora
        char verificarHora = evt.getKeyChar();
        if (Character.isLetter(verificarHora)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "SOLO SE PERMITEN CARACTERES NÚMERICOS");
        }
    }//GEN-LAST:event_horaKeyTyped

    private void IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDKeyTyped
        //Aca verifico que solo se perimitan numero en el ID
        char verificarID = evt.getKeyChar();
        if (Character.isLetter(verificarID)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "SOLO SE PERMITEN CARACTERES NÚMERICOS");
        }
    }//GEN-LAST:event_IDKeyTyped

    public CitaAgendada DatosGuardados;
    
    private void ButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarActionPerformed
        //Aca se guardan los datos ingresados

        int Ndocumento;
        int CitaTelefono;
        int CitaFecha;
        int CitaHora;

        String CitaGenero = "";
        String CitaConsultorio = "";
        String CitaHorario = "";
        String ServicioMedico = "";

        Ndocumento = Integer.parseInt(ID.getText());
        CitaFecha = Integer.parseInt(TFielFechaCita.getText());
        CitaHora = Integer.parseInt(hora.getText());

        CitaGenero = BoxGenero.getSelectedItem().toString();
        CitaConsultorio = BoxConsultorio.getSelectedItem().toString();
        CitaHorario = BoxHorario.getSelectedItem().toString();
        ServicioMedico = BoxServicio.getSelectedItem().toString();

        if (!ValidarUsuario(ID.getText())) {
            JOptionPane.showMessageDialog(rootPane, "DEBE AFILIARSE PRIMERO");
            return;
        }

        DatosGuardados = new CitaAgendada(
                Ndocumento, 0, CitaFecha, CitaHora,
                "", "",
                CitaGenero, CitaConsultorio,
                ServicioMedico
        );

        this.almacenamiento.getCitas().add(DatosGuardados);
        Citastxt citastxt = new Citastxt();
        citastxt.crearArchivo();
        citastxt.EscribirArchivo(DatosGuardados);
        JOptionPane.showMessageDialog(rootPane, "SE HA GUARDADO CORRECTAMENTE");
        Limpiar();
    }//GEN-LAST:event_ButtonGuardarActionPerformed

    private void TFielFechaCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFielFechaCitaActionPerformed
        // Aca bloqueo el text fiel
    }//GEN-LAST:event_TFielFechaCitaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxConsultorio;
    private javax.swing.JComboBox<String> BoxGenero;
    private javax.swing.JComboBox<String> BoxHorario;
    private javax.swing.JComboBox<String> BoxServicio;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JButton ButtonLimpiar;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField TFielFechaCita;
    private javax.swing.JTextField hora;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        ID.setText("");
        hora.setText("");
    }
}
