/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a.miniproyecto3;

import java.awt.Color;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import java.lang.reflect.Array;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author JHOIMAR
 */
public class VentanaAdministracion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdministracion
     */
    private DefaultTableModel modelo;
    private Almacenamiento almacenamiento;
    private VentanaLogin padre;

    public VentanaAdministracion(
            Almacenamiento almacenamiento
    ) {
        initComponents();
        setSize(650, 510);
        setLocationRelativeTo(null);
        setResizable(false);
        setMinimumSize(new Dimension(200, 200));
        this.getContentPane().setBackground(Color.white);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        this.almacenamiento = almacenamiento;
        this.modelo = (DefaultTableModel) this.jTable1.getModel();
    }

    public void setPadre(VentanaLogin padre) {
        this.padre = padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ButtonGuardar = new javax.swing.JButton();
        ButtonModificar = new javax.swing.JButton();
        ButtonEliminar = new javax.swing.JButton();
        ButtonBuscar = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        FieldDocumento = new javax.swing.JTextField();
        tFielNombrecompleto = new javax.swing.JTextField(0);
        TFielFechaNac = new javax.swing.JTextField();
        TFielDireccion = new javax.swing.JTextField();
        TFielGenero = new javax.swing.JTextField();
        TFielServicio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ADMINISTRADOR DE CITAS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 10, 330, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("DOCUMENTO:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 94, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NOMBRE COMPLETO:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 100, 143, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("FECHA DE NACIMIENTO:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 140, 200, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("DIRECCIÓN:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 180, 100, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("GENERO:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 220, 90, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("SERVICIO MEDICO SOLICITADO: ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 260, 220, 20);

        ButtonGuardar.setText("GUARDAR");
        ButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonGuardar);
        ButtonGuardar.setBounds(510, 100, 120, 23);

        ButtonModificar.setText("MODIFICAR");
        ButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonModificar);
        ButtonModificar.setBounds(510, 140, 120, 23);

        ButtonEliminar.setText("ELIMINAR");
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonEliminar);
        ButtonEliminar.setBounds(510, 180, 120, 23);

        ButtonBuscar.setText("BUSCAR");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonBuscar);
        ButtonBuscar.setBounds(510, 60, 120, 23);

        ButtonSalir.setText("SALIR");
        ButtonSalir.setToolTipText("");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSalir);
        ButtonSalir.setBounds(510, 220, 120, 23);

        FieldDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldDocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(FieldDocumento);
        FieldDocumento.setBounds(250, 60, 250, 22);

        tFielNombrecompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFielNombrecompletoActionPerformed(evt);
            }
        });
        jPanel1.add(tFielNombrecompleto);
        tFielNombrecompleto.setBounds(250, 100, 250, 22);
        jPanel1.add(TFielFechaNac);
        TFielFechaNac.setBounds(250, 140, 250, 22);
        jPanel1.add(TFielDireccion);
        TFielDireccion.setBounds(250, 180, 250, 22);
        jPanel1.add(TFielGenero);
        TFielGenero.setBounds(250, 220, 250, 22);
        jPanel1.add(TFielServicio);
        TFielServicio.setBounds(250, 260, 250, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Servicio", "Paciente", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 302, 620, 160);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarActionPerformed
        // Aca va el boton de guardar
        String Id = FieldDocumento.getText();
        String Fecha = TFielFechaNac.getText();
        String Servicio = TFielServicio.getText();
        String Nombre = tFielNombrecompleto.getText();
        String Telefono = FieldDocumento.getText();
        Vector Guardar = new Vector();
        Guardar.add(Id);
        Guardar.add(Fecha);
        Guardar.add(Servicio);
        Guardar.add(Nombre);
        Guardar.add(Telefono);
         this.modelo.addRow(Guardar);
        
        
    }//GEN-LAST:event_ButtonGuardarActionPerformed

    private void ButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonModificarActionPerformed

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEliminarActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        // Aca va el boton pa atras
        this.padre.volver();
    }//GEN-LAST:event_ButtonSalirActionPerformed

    public String ValidarUsuario(String Id) {
        boolean i = false;
        String actual = "";
        try {
            BufferedReader escritura = new BufferedReader(new FileReader("Citas.txt"));
            String posicion = "";
            
            while ((posicion = escritura.readLine()) != null) {
                if (posicion.indexOf(Id) != -1) {
                    System.out.println("Se encontró el registro" + posicion);
                    i = true;
                    actual = posicion;
                }
            }
        } catch (IOException e) {
            System.out.println(e);
        }
        
        return actual;
    }
    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
       String documento =(FieldDocumento.getText());
       String Validacion = ValidarUsuario(documento)+"*";
       int i = 0;
       int l = 0;
       int NoPacientes = Validacion.length();
       //Vector data = new Vector();
       String data [] = new String[8];
       String dato = "";
       for (i = 0; i <= NoPacientes; i++ ) {
           if ('*'!=Validacion.charAt(i)) {
               dato += Validacion.charAt(i);
           }
           else  {
               data[l] = dato;
               System.out.println(dato);
               tFielNombrecompleto.setText(data[3]);
                TFielFechaNac.setText(data[4]);
                TFielDireccion.setText(data[5]);
                TFielGenero.setText(data[6]);
                TFielServicio.setText(data[7]);
               l = l + 1;
               dato = "";
               
               if(i == NoPacientes ){
                   this.modelo.addRow(data);
               }
               //JOptionPane.showMessageDialog(rootPane, "NO SE HA ENCONTRADO EL USUARIO");
           }  //data.add(dato);
           
           
           /*Vector retorno = new Vector();
           retorno.add(data.get(0));
           retorno.add( data.get(4));
           retorno.add( data.get(5));
           retorno.add(data.get(6));
           retorno.add(data.get(7));
           this.modelo.addRow(retorno);*/   
       }
        
        System.out.println(data[1]+"Esta es la prueba final si Dios quiere");
        /* int index = 0;
        int documento = Integer.parseInt(FieldDocumento.getText());

        this.modelo.setRowCount(0);

        for (CitaAgendada cita : almacenamiento.getCitas()) {
            if (cita.getNumeroDocumento() == documento) {
                Vector data = new Vector();

                data.add(index++); // ID
                data.add(cita.getFechaCita()); // Fecha
                data.add(cita.getServicioMedico()); // Servicio 
                data.add(cita.getNombrePaciente()); //Paciente
                data.add(cita.getTelefonoPaciente()); //Telefono

                this.modelo.addRow(data);
            }
        }*/
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void tFielNombrecompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFielNombrecompletoActionPerformed
        // Desahabilitar boton

    }//GEN-LAST:event_tFielNombrecompletoActionPerformed

    private void FieldDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldDocumentoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JButton ButtonModificar;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JTextField FieldDocumento;
    private javax.swing.JTextField TFielDireccion;
    private javax.swing.JTextField TFielFechaNac;
    private javax.swing.JTextField TFielGenero;
    private javax.swing.JTextField TFielServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tFielNombrecompleto;
    // End of variables declaration//GEN-END:variables
}
